apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-app.fullname" . }}-secret
type: Opaque
stringData:
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_USER: {{ .Values.database.username | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
