apiVersion: v1
kind: Pod
metadata:
  name: toleration-test
spec:
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "database"
      effect: "NoSchedule"

  containers:
    - name: nginx
      image: nginx:alpine
